#!/usr/bin/env bash
# Record a *real* Iris session and turn it into an animated SVG hero.
#
# The committed README hero (docs/assets/hero-{dark,light}.svg) is a faithful,
# theme-adaptive reproduction generated by scripts/gen-hero-svg.py. This script
# is the alternative: capture an actual session with asciinema and render it to
# an animated SVG via svg-term. Use it when you want the hero to be a genuine
# recording rather than a hand-built reproduction.
#
# Requirements:
#   - asciinema   (https://asciinema.org)        record the cast
#   - npx + svg-term-cli (fetched on demand)      cast -> animated SVG
#
# Usage:
#   scripts/record-demo.sh                # record, then render docs/assets/hero-cast.svg
#   scripts/record-demo.sh existing.cast  # skip recording, render an existing cast
#
# After rendering, point the README <picture> at hero-cast.svg (a recording is a
# single theme; drop the light/dark <source> pair and use one <img>).
set -euo pipefail

cd "$(dirname "$0")/.."
OUT_DIR="docs/assets"
CAST="${1:-$OUT_DIR/iris-demo.cast}"
SVG="$OUT_DIR/hero-cast.svg"
COLS="${IRIS_DEMO_COLS:-84}"
ROWS="${IRIS_DEMO_ROWS:-26}"

mkdir -p "$OUT_DIR"

if [ "$#" -eq 0 ]; then
  command -v asciinema >/dev/null 2>&1 || {
    echo "error: asciinema not found. Install it, or pass an existing .cast file." >&2
    exit 1
  }
  echo "Recording a ${COLS}x${ROWS} session into $CAST."
  echo "Drive Iris through one tight turn (a task, a tool call, a result), then /exit."
  echo
  asciinema rec --cols "$COLS" --rows "$ROWS" --overwrite "$CAST" -c "${IRIS_BIN:-cargo run --}"
fi

[ -f "$CAST" ] || { echo "error: cast file not found: $CAST" >&2; exit 1; }

echo "Rendering $CAST -> $SVG"
# Palette tracks DESIGN.md (dark reference approximations of the ANSI roles).
npx -y svg-term-cli \
  --in "$CAST" --out "$SVG" \
  --window --no-cursor \
  --term iterm2 --profile "$OUT_DIR/iris.itermcolors" 2>/dev/null \
  || npx -y svg-term-cli --in "$CAST" --out "$SVG" --window

echo "Done. Preview $SVG, then wire it into the README <picture> if you prefer the live cast."
