use std::cell::RefCell;
use std::collections::HashSet;
use std::future::Future;
use std::path::Path;
use std::pin::Pin;
use std::time::Duration;

use anyhow::{Error, Result, bail};
use futures::Stream;
use futures::StreamExt;
use serde_json::{Value, json};
use tokio_util::sync::CancellationToken;

// The agent loop has no built-in fixed turn cap: it runs while the model keeps
// emitting tool calls and ends naturally when the model stops (matching
// pi-mono's `runLoop`, which has no maxTurns/maxSteps). Cancellation (Ctrl-C) is
// the always-on runaway guard. An optional soft cap can be supplied via
// `Settings` (`Agent::max_tool_roundtrips`); when set it ends the turn with a
// graceful Notice rather than a fatal error (see complete_turn).

// Oversized-tool-output policy (issue #61). A successful tool result whose text
// exceeds this many bytes is stored out of context behind a handle and replaced
// in the transcript by a compact head+tail preview, so a large output is not
// reinserted into provider context on every round-trip. Outputs at or below the
// threshold stay inline exactly as before.
//
// ponytail: fixed default. Matches pi-mono's 50 KB truncate threshold
// (`harness/utils/truncate.ts` DEFAULT_MAX_BYTES). Covers ordinary tool output
// (file reads, small greps) inline and catches genuinely large logs. Upgrade
// path = a `Settings` knob threaded through `ToolEnv` (kept a constant here to
// avoid a config field that triggers nothing, like `contextTokenBudget` already
// is). Bytes, not lines: context cost tracks bytes/tokens, not line count.
const MAX_INLINE_TOOL_OUTPUT_BYTES: usize = 50 * 1024;

// Head/tail kept in the compact preview of an offloaded output. Their sum is
// well under MAX_INLINE_TOOL_OUTPUT_BYTES, so an offloaded result is always
// smaller than the threshold it crossed, and head/tail never overlap (offloaded
// content is strictly larger than head+tail).
const PREVIEW_HEAD_BYTES: usize = 4 * 1024;
const PREVIEW_TAIL_BYTES: usize = 2 * 1024;

// Shared between every cancellation exit path so the front-end renders one
// consistent message whether the interrupt landed before, during, or after the
// provider stream.
const INTERRUPT_NOTICE: &str = "interrupted; send another message to continue.";

/// Outcome of an approval review for a single tool call. Provider/UI-neutral so
/// the core loop owns the approval policy without depending on any front-end.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ApprovalDecision {
    /// Allow this one call.
    Allow,
    /// Allow this call and auto-approve later calls of the same tool for the
    /// rest of the session. Nexus owns and enforces that session policy.
    AllowAlways,
    /// Refuse this call. Default for empty/invalid/EOF input (safe-by-default).
    Deny,
}

/// The semantic events the loop emits during a turn. Provider- and UI-neutral:
/// a front-end maps these onto its own rendering. Mirrors pi's `AgentEvent`
/// union (`packages/agent/src/types.ts`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum AgentEvent {
    /// One provider/model round trip is starting. The id is generated by Nexus
    /// and tags the messages/events produced by this provider response.
    ProviderTurnStarted {
        turn_id: String,
    },
    /// One provider/model round trip completed with a terminal provider event.
    /// `response_id` is the provider's opaque response id when reported; `usage`
    /// carries provider token/cache accounting. Both are safe metadata and keep
    /// provider diagnostics observable without surfacing request/response bodies.
    ProviderTurnCompleted {
        turn_id: String,
        response_id: Option<String>,
        usage: Option<ProviderUsage>,
        /// Provider-neutral reason the model turn ended, when the provider
        /// reports one. Safe metadata: an enumerated completion classification,
        /// never response text. `None` for providers that do not surface it.
        completion_reason: Option<CompletionReason>,
    },
    /// One provider/model round trip was interrupted before completion.
    ProviderTurnCancelled {
        turn_id: String,
    },
    /// One provider/model round trip failed. The message is the same sanitized
    /// boundary error Iris already surfaces; provider request/response payloads
    /// and auth material are never attached to the event.
    ProviderTurnError {
        turn_id: String,
        message: String,
    },
    /// Provider-neutral tool lifecycle metadata for observability. The existing
    /// display events remain for UI compatibility; this compact event carries
    /// only ids/state and never includes tool arguments, output, provider
    /// payloads, paths, or secrets.
    ToolLifecycle {
        provider_turn_id: String,
        call_id: String,
        name: String,
        state: ToolEventState,
    },
    /// A large successful tool output was offloaded behind a session-scoped
    /// handle. Metadata only: the full body and preview are intentionally not
    /// carried by this observability event.
    OutputHandleStored {
        provider_turn_id: String,
        call_id: String,
        handle_id: String,
        bytes: usize,
        lines: usize,
    },
    /// The harness compacted persisted context at a safe turn boundary.
    /// Contains ids and token estimates, not the generated summary text.
    CompactionApplied {
        compaction_id: String,
        covered_from: String,
        covered_to: String,
        covered_messages: usize,
        original_tokens_estimate: u64,
        summary_tokens_estimate: u64,
        budget: u64,
    },
    AssistantText(String),
    AssistantTextDelta(String),
    AssistantTextEnd(String),
    /// One block of model reasoning ("thinking") surfaced for display. Reasoning
    /// arrives as whole blocks at turn completion (the provider stream does not
    /// expose incremental reasoning deltas here), so this is emitted once per
    /// block, not as a stream. Display-only: emitting it never changes what is
    /// stored (the reasoning row is still persisted, ADR-0016) or sent to the
    /// provider. A `redacted` block carries no text -- the provider withheld it,
    /// so the original reasoning text is never reconstructed or rendered; the
    /// front-end shows only that redacted reasoning occurred.
    AssistantReasoning {
        text: String,
        redacted: bool,
    },
    ToolProposed(ToolCall),
    /// A tool is about to execute (emitted once per call, immediately before the
    /// run, on both the exclusive and parallel paths). Lets a front-end open a
    /// live progress cell before any output arrives. Display-only.
    ToolStarted(ToolCall),
    /// A gated tool was auto-approved by the session allow-policy. Emitted by
    /// Nexus, never inferred by a front-end, so the policy stays Nexus-owned.
    ToolAutoApproved(ToolCall),
    DiffPreview {
        call: ToolCall,
        diff: String,
    },
    ToolDenied(ToolCall),
    ToolResult {
        call: ToolCall,
        content: String,
        /// Process exit code for a shell-like tool (`Some(0)`/`None` is success,
        /// non-zero is failure). `None` for tools that have no exit status.
        exit_code: Option<i32>,
        /// Wall-clock execution time, when the tool reports it.
        duration: Option<Duration>,
    },
    /// A display-only chunk of a running tool's live output (issue #90 sub-item
    /// 1). Carries the originating call id so a front-end attaches it to the
    /// right live cell. NEVER pushed to `self.messages`: the full output reaches
    /// provider context once, via the tool's final `ToolResult`.
    ToolOutputDelta {
        call_id: String,
        chunk: String,
    },
    ToolError {
        call: ToolCall,
        message: String,
    },
    ToolCancelled(ToolCall),
    /// A user message the loop injected mid-run: a steering or follow-up message
    /// the host queued while the turn was running. Emitted so the front-end
    /// renders the user row in transcript order. The initial prompt is NOT
    /// emitted (the front-end commits that itself); only injected messages are.
    /// The message is also pushed into provider context.
    UserMessage(String),
    Notice(String),
    TurnComplete,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ToolEventState {
    Proposed,
    ApprovalRequested,
    Approved,
    Denied,
    Started,
    Succeeded,
    Errored,
    Cancelled,
}

/// A provider-neutral streamed model event. The async [`ChatProvider`] yields a
/// sequence of these instead of one blocking whole-turn result, so the loop can
/// race each read against cancellation. Mirrors Codex's `ResponseEvent`
/// (`core/src/client.rs`): incremental text deltas, then one terminal
/// `Completed` carrying the assembled turn (text + tool calls).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ProviderEvent {
    /// Incremental assistant text.
    TextDelta(String),
    /// Terminal event: the fully assembled assistant turn.
    Completed(AssistantTurn),
}

/// A `!Send` boxed stream of provider events tied to the borrow of the provider
/// and its inputs. Boxed (not `impl Stream`) so the loop code is uniform and the
/// real provider can back it with a channel fed by a blocking task.
pub(crate) type ProviderStream<'a> = Pin<Box<dyn Stream<Item = Result<ProviderEvent>> + 'a>>;

/// A `!Send` boxed tool-execution future, so `Box<dyn Tool>` stays object-safe
/// while `execute` is async.
pub(crate) type ToolFuture<'a> = Pin<Box<dyn Future<Output = Result<ToolOutput>> + 'a>>;

/// A `!Send` boxed approval future, so `&dyn ApprovalGate` stays object-safe
/// while `review` is async (and therefore raceable against cancellation).
pub(crate) type ApprovalFuture<'a> = Pin<Box<dyn Future<Output = Result<ApprovalDecision>> + 'a>>;

/// Fire-and-forget event sink the loop emits to. `&self` with no control-flow
/// return; errors only propagate. Mirrors pi's standalone `AgentEventSink`
/// passed as a separate argument, not a config field.
pub(crate) trait AgentObserver {
    fn on_event(&self, event: AgentEvent) -> Result<()>;
}

/// Persists oversized tool output outside provider context so the transcript
/// carries a compact handle instead of the full payload (issue #61). The Tier-2
/// Wayland harness implements it over local session storage; Nexus owns only
/// this contract and the threshold/compaction policy and never touches the
/// filesystem itself, mirroring [`ApprovalGate`]/[`ChatProvider`].
pub(crate) trait ToolOutputStore {
    /// Persist the full output text and return a stable handle id. The id must
    /// be stable for identical content so a resumed transcript keeps pointing at
    /// the same stored output (the harness impl is content-addressed).
    fn put(&self, content: &str) -> Result<String>;
}

/// Display-only live-output sink for a running tool (issue #90 sub-item 1). A
/// long-running tool (today only `bash`) forwards each output chunk here as it
/// is produced; Nexus wraps it per-call and re-emits an
/// [`AgentEvent::ToolOutputDelta`] so the front-end can stream the command's
/// output live. `None` keeps a tool non-streaming (the parallel/exploration
/// path and tests inject `None`). Chunks are display-only and NEVER enter
/// provider context. Mirrors the optional [`ToolOutputStore`] seam.
pub(crate) trait ToolOutputSink {
    /// Forward one freshly produced output chunk (lossy-UTF-8 decoded) to the
    /// front-end. Best-effort: a delivery failure never aborts the tool.
    fn emit_chunk(&self, chunk: &str);
}

/// Source of mid-run user messages the host queued while a turn was running.
/// Provider- and UI-neutral, like [`ApprovalGate`]: Nexus owns the contract and
/// the injection points; the Tier-3 app backs it with the user's typed queue and
/// owns the drain policy (how many queued messages each poll yields). Mirrors
/// pi's `getSteeringMessages` / `getFollowUpMessages` loop hooks
/// (`packages/agent/src/types.ts`).
///
/// - **Steering** messages are injected before the next provider request (after
///   the current round's tool calls finish), so they redirect work in flight.
/// - **Follow-up** messages are injected only when the agent would otherwise
///   stop (no tool calls and no steering), continuing the run with another turn.
///
/// Both drains are synchronous and must not block: the in-memory queue is polled
/// from inside the loop between awaits. Each returns an empty vec when nothing is
/// queued.
pub(crate) trait SteeringSource {
    /// Drain the steering messages to inject before the next provider request.
    fn take_steering(&self) -> Vec<String>;
    /// Drain the follow-up messages to inject after the agent would stop.
    fn take_follow_up(&self) -> Vec<String>;
}

/// Request/response approval gate. Async so the loop can race a pending approval
/// against cancellation (`tokio::select!`); the loop branches on the returned
/// decision to control execution. Mirrors pi's `beforeToolCall` config hook,
/// which the loop inspects via `{ block }` -- a seam distinct from the event
/// sink.
pub(crate) trait ApprovalGate {
    /// `allow_always` mirrors the tool's [`Tool::supports_allow_always`] so the
    /// front-end only offers an "always allow" choice the loop will honor (shell
    /// tools opt out, so their prompt is y/N only).
    fn review<'a>(&'a self, call: &'a ToolCall, allow_always: bool) -> ApprovalFuture<'a>;
}

/// Structured result of a successful tool call: the model-facing text plus
/// optional structured metadata. Tier-1 result contract (the analogue of pi's
/// `AgentToolResult`); tools with nothing structured to report use
/// [`ToolOutput::text`] and the metadata is omitted from the wire.
#[derive(Debug)]
pub(crate) struct ToolOutput {
    pub(crate) content: String,
    pub(crate) metadata: serde_json::Map<String, Value>,
}

impl ToolOutput {
    /// A text-only result with no structured metadata.
    pub(crate) fn text(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            metadata: serde_json::Map::new(),
        }
    }

    /// Attach one metadata field, builder-style.
    pub(crate) fn with(mut self, key: &str, value: Value) -> Self {
        self.metadata.insert(key.to_string(), value);
        self
    }
}

/// Execution environment handed to a tool: the workspace root plus the shared
/// per-session tool state (observed files, bash sessions). The state is behind a
/// [`RefCell`] so the loop can hand a shared `&ToolEnv` to several
/// concurrency-safe tools at once (safe-parallel execution); each tool's body is
/// synchronous and never holds the borrow across an `.await`. Owned by the
/// Tier-2 Wayland harness and injected into each turn, mirroring how pi's
/// `AgentHarness` feeds its `ExecutionEnv` into the loop. `ToolState` is defined
/// in `crate::tools`.
pub(crate) struct ToolEnv<'a> {
    pub(crate) workspace: &'a Path,
    pub(crate) state: &'a RefCell<crate::tools::ToolState>,
    /// Optional out-of-context store for oversized tool outputs (issue #61).
    /// `None` keeps every output inline (no durable session storage available),
    /// preserving the original in-memory behavior. Harness-owned, injected here.
    pub(crate) output_store: Option<&'a dyn ToolOutputStore>,
    /// Optional live-output sink for streaming a running tool's output (issue
    /// #90 sub-item 1). `None` (the harness default) keeps the tool
    /// non-streaming; Nexus injects a per-call sink on the exclusive path so a
    /// streaming tool's chunks reach the front-end as display-only deltas.
    pub(crate) output_sink: Option<&'a dyn ToolOutputSink>,
}

/// A tool the agent can invoke. Mirrors pi-ai's `Tool`
/// (`name`/`description`/`parameters`) plus pi-agent's `AgentTool` (the tool
/// runs itself via `execute`). Nexus enforces the approval policy, but each tool
/// *classifies* itself, so the core loop never matches on tool names.
pub(crate) trait Tool {
    fn name(&self) -> &str;
    fn description(&self) -> &str;
    /// JSON Schema for the arguments, used to build provider tool declarations.
    fn parameters(&self) -> Value;
    /// Run the tool. Async + given a child [`CancellationToken`]: a long-running
    /// tool (e.g. shell) should observe the token and stop promptly. The loop
    /// also races this future against the token, so a tool that ignores it is
    /// still abandoned (with a synthetic cancelled result).
    fn execute<'a>(
        &'a self,
        args: &'a Value,
        env: &'a ToolEnv<'_>,
        cancel: CancellationToken,
    ) -> ToolFuture<'a>;

    /// Whether this tool may run concurrently with other concurrency-safe tools
    /// in the same model turn. Default: exclusive. Only read-only tools whose
    /// behavior is unaffected by concurrent peers opt in; the loop never runs an
    /// exclusive tool alongside anything else.
    fn is_concurrency_safe(&self) -> bool {
        false
    }

    /// Whether a call to this tool must be approved before it runs.
    fn requires_approval(&self) -> bool {
        false
    }
    /// Whether these arguments perform a destructive, data-losing operation that
    /// must be re-approved every time, even when the tool is "always allowed".
    fn is_destructive(&self, _args: &Value) -> bool {
        false
    }
    /// Whether an "always allow" decision may persist for this tool. Tools that
    /// authorize arbitrary later effects (e.g. shell) opt out, so the loop keeps
    /// prompting each call instead of name-matching `"bash"` in core.
    fn supports_allow_always(&self) -> bool {
        true
    }
    /// Optional pre-approval diff preview (Tier-3 presentation). `None` when the
    /// tool has no preview or the arguments are malformed.
    fn diff_preview(&self, _workspace: &Path, _args: &Value) -> Option<String> {
        None
    }
}

/// Provider/model capability snapshot the tool-surface planner reads to decide
/// which built-in tools are *model-visible*. Provider-neutral (Tier 1): each
/// provider reports its own via [`ChatProvider::capabilities`], and the planner
/// ([`Tools::plan_surface`]) maps it to the advertised tool set. The default
/// exposes the full built-in surface, so every provider that does not override
/// keeps today's exact behavior.
///
/// This narrows only what the model *sees*; execution lookup ([`Tools::by_name`])
/// is unaffected, so a hidden tool a resumed transcript still references stays
/// runnable. Conceptually mirrors Codex's split between a tool registry
/// (execution) and `model_visible_specs` (declarations) without porting its
/// planner.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(crate) struct ProviderCapabilities {
    /// The provider/model carries a native code-edit affordance (e.g. Codex
    /// `apply_patch`, V4A) that supersedes the generic `edit` tool, so `edit` is
    /// dropped from the model-visible surface. The native replacement tool is a
    /// later slice (ROADMAP #10 provider-specific tools); no provider sets this
    /// today, so the surface is unchanged.
    pub(crate) native_edit: bool,
}

impl ProviderCapabilities {
    /// Whether a tool with this name is advertised to the model under these
    /// capabilities. The single rule today: a provider with a native edit
    /// affordance hides the generic `edit` tool. Any other name is exposed
    /// (fail-open), so missing or partial capability data falls back to today's
    /// full surface.
    fn exposes(&self, tool_name: &str) -> bool {
        !(self.native_edit && tool_name == "edit")
    }
}

/// Injected collection the agent resolves tool calls against. A thin name lookup
/// over a `Vec<Box<dyn Tool>>` -- no identity keys, override, or dispatch-order
/// machinery (that is issue #18, out of scope). Mirrors pi's `context.tools`
/// resolved with `tools.find(t => t.name === toolCall.name)`.
///
/// The set distinguishes the *model-visible* surface ([`iter`](Self::iter), used
/// to build provider declarations) from the full *execution* registry
/// ([`by_name`](Self::by_name)). They are deliberately separate: the planner can
/// hide a tool from the model while keeping it runnable, the seam
/// provider-specific tool surfaces (ROADMAP #10) build on.
pub(crate) struct Tools {
    tools: Vec<Box<dyn Tool>>,
    /// Capabilities of the provider/model this set is advertised to.
    /// [`iter`](Self::iter) (model-visible declarations) filters by this;
    /// [`by_name`](Self::by_name) (execution) ignores it. Defaults to full
    /// exposure, so a freshly built set advertises every tool until a planner
    /// narrows it.
    caps: ProviderCapabilities,
}

impl Tools {
    pub(crate) fn new(tools: Vec<Box<dyn Tool>>) -> Self {
        Self {
            tools,
            caps: ProviderCapabilities::default(),
        }
    }

    /// Resolve a call by exact tool name over the *full* registry. `None` for an
    /// unknown tool. Independent of the model-visible plan: a tool hidden by
    /// [`plan_surface`](Self::plan_surface) still resolves here, so execution,
    /// approval, and cancellation behavior never depends on visibility.
    pub(crate) fn by_name(&self, name: &str) -> Option<&dyn Tool> {
        self.tools
            .iter()
            .map(|tool| &**tool)
            .find(|tool| tool.name() == name)
    }

    /// Iterate the *model-visible* tools in declaration order (for provider tool
    /// schemas). Reflects the planned surface, not the full registry.
    pub(crate) fn iter(&self) -> impl Iterator<Item = &dyn Tool> {
        self.tools
            .iter()
            .map(|tool| &**tool)
            .filter(|tool| self.caps.exposes(tool.name()))
    }

    /// Plan the model-visible surface for a provider/model with these
    /// capabilities. The registry (every tool) is untouched, so [`by_name`](Self::by_name)
    /// still resolves hidden tools for execution; only the advertised
    /// [`iter`](Self::iter) surface shrinks. This is the planner seam: it records
    /// the capabilities the surface is planned against, never branching inside
    /// tool execution.
    fn plan_surface(&mut self, caps: &ProviderCapabilities) {
        self.caps = *caps;
    }
}

pub(crate) trait ChatProvider {
    /// Begin a streamed model response. Providers translate their native wire
    /// format into a stream of Nexus-owned [`ProviderEvent`]s; setup errors
    /// (e.g. a bad URL) surface synchronously via the `Result`, stream errors
    /// arrive as `Err` items. `tools` is the injected set the provider
    /// advertises as callable declarations. `cancel` is the turn token: a
    /// provider that does blocking work off-thread should observe it so a
    /// cancelled turn stops issuing/retrying requests instead of running to
    /// completion in the background.
    fn respond_stream<'a>(
        &'a self,
        messages: &'a [Message],
        tools: &'a Tools,
        cancel: &'a CancellationToken,
    ) -> Result<ProviderStream<'a>>;

    /// The provider/model capabilities the tool-surface planner reads to decide
    /// the model-visible tool set. Default: the full built-in surface (today's
    /// behavior). A provider overrides this only to vary which tools the model
    /// sees; tool execution is never affected.
    fn capabilities(&self) -> ProviderCapabilities {
        ProviderCapabilities::default()
    }
}

/// Forward the contract through a boxed provider so the front-end can select
/// one of several concrete providers at runtime (`Box<dyn ChatProvider>`)
/// without making every downstream type generic over the choice.
impl ChatProvider for Box<dyn ChatProvider> {
    fn respond_stream<'a>(
        &'a self,
        messages: &'a [Message],
        tools: &'a Tools,
        cancel: &'a CancellationToken,
    ) -> Result<ProviderStream<'a>> {
        (**self).respond_stream(messages, tools, cancel)
    }

    fn capabilities(&self) -> ProviderCapabilities {
        (**self).capabilities()
    }
}

pub(crate) struct Agent<P> {
    pub(crate) provider: P,
    messages: Vec<Message>,
    // Injected tool set, constructed at Tier 3 and resolved by name in the loop.
    // Core names no concrete tool; it only holds the `Tool` contract.
    tools: Tools,
    // Session approval policy: tool names the user chose to "always" allow.
    // Owned and enforced here in Nexus, not in the UI, so a front-end can never
    // silently widen what runs without approval. Granularity is per tool name.
    // ponytail: per-tool-name always-allow. The mutating tools (`bash`, `write`,
    // `edit`) opt out (`supports_allow_always() == false`), so an "always" on
    // them never sticks and every call re-prompts -- a blanket allow would
    // authorize arbitrary later effects. Upgrade path = per-exact-command/path
    // keys (e.g. `bash:<cmd>`, `write:<path>`) once a real audit trail exists
    // (roadmap #14).
    session_allowed: HashSet<String>,
    // Provider/model round-trip id sequence. Nexus owns these ids because it
    // owns the provider loop; Wayland may persist them, but never mints them.
    next_provider_turn_seq: u32,
    // Optional graceful soft cap on tool round-trips per turn. `None` (default)
    // = unbounded: the loop runs while the model emits tool calls, matching
    // pi-mono. When `Some(n)`, the loop ends the turn with a Notice after `n`
    // round-trips instead of a fatal error. Cancellation remains the always-on
    // runaway guard regardless. Supplied by the host from `Settings`.
    max_tool_roundtrips: Option<usize>,
}

/// Result of consuming one provider stream to its terminal event (or to a
/// cancellation). Owned so the borrow of `self.messages`/`self.tools` taken by
/// the stream is released before the loop mutates the transcript.
enum StreamResult {
    Completed {
        turn: AssistantTurn,
        saw_delta: bool,
    },
    Cancelled {
        partial: String,
        saw_delta: bool,
    },
}

/// Whether the tool phase wants another model round-trip or ended the turn
/// itself (a cancellation already emitted `TurnComplete`).
enum ToolsPhase {
    Continue,
    Ended,
}

/// Internal per-call execution outcome, mapped to a transcript message + event
/// by [`record_call`].
enum ToolOutcome {
    Ok(ToolOutput),
    Err(anyhow::Error),
    Cancelled,
    Denied,
}

impl<P: ChatProvider> Agent<P> {
    /// A bare, in-memory agent: it owns the provider, conversation, injected
    /// tools, and approval policy, but no filesystem or persistence. Mirrors
    /// pi's bare `Agent`; the Tier-2 Wayland harness wraps it with the execution
    /// env and session store.
    pub(crate) fn new(provider: P, mut tools: Tools) -> Self {
        // Plan the model-visible surface once, from the provider's declared
        // capabilities. Default capabilities expose the full built-in set, so
        // every provider keeps today's surface unless it opts to vary it.
        tools.plan_surface(&provider.capabilities());
        Self {
            provider,
            messages: Vec::new(),
            tools,
            session_allowed: HashSet::new(),
            next_provider_turn_seq: 0,
            max_tool_roundtrips: None,
        }
    }

    /// Install an optional graceful soft cap on tool round-trips per turn.
    /// `None` keeps the default unbounded loop; `Some(n)` ends the turn with a
    /// Notice after `n` round-trips. The host threads the configured value from
    /// `Settings` exactly like the context token budget.
    pub(crate) fn with_max_tool_roundtrips(mut self, cap: Option<usize>) -> Self {
        self.max_tool_roundtrips = cap;
        self
    }

    /// A bare agent seeded with a prior conversation, for resuming a session.
    /// The reconstructed `messages` become the provider-visible context for the
    /// next turn; the approval policy starts fresh (allow-always is per-process,
    /// not persisted). Mirrors pi's harness loading session entries and
    /// rebuilding context before continuing the conversation.
    pub(crate) fn resumed(provider: P, mut tools: Tools, mut messages: Vec<Message>) -> Self {
        repair_dangling_tool_call(&mut messages);
        let next_provider_turn_seq = next_provider_turn_seq(&messages);
        tools.plan_surface(&provider.capabilities());
        Self {
            provider,
            messages,
            tools,
            session_allowed: HashSet::new(),
            next_provider_turn_seq,
            max_tool_roundtrips: None,
        }
    }

    /// Read access to the in-memory transcript so the harness can persist it
    /// without the core loop owning a session store.
    pub(crate) fn messages(&self) -> &[Message] {
        &self.messages
    }

    /// Replace the in-memory provider-visible context. The Tier-2 harness uses
    /// this to install a compacted context (summary + retained tail) before the
    /// next turn; the bare agent stays oblivious to compaction policy and
    /// persistence, just as [`resumed`](Self::resumed) seeds context on resume.
    pub(crate) fn replace_messages(&mut self, messages: Vec<Message>) {
        self.messages = messages;
    }

    /// Swap the active provider at a safe turn boundary and re-plan the
    /// model-visible tool surface from the new provider's capabilities. The
    /// Tier-3 app rebuilds a provider on a `/model` `/reasoning` switch and
    /// installs it here; the in-memory conversation and approval policy are
    /// untouched, so the next turn runs against the new provider with the same
    /// context. Mirrors [`new`](Self::new)/[`resumed`](Self::resumed) planning
    /// the surface once from the provider's capabilities.
    pub(crate) fn replace_provider(&mut self, provider: P) {
        self.provider = provider;
        self.tools.plan_surface(&self.provider.capabilities());
    }

    pub(crate) async fn submit_turn(
        &mut self,
        prompt: &str,
        obs: &dyn AgentObserver,
        gate: &dyn ApprovalGate,
        env: &ToolEnv<'_>,
        token: &CancellationToken,
        steer: Option<&dyn SteeringSource>,
    ) -> Result<()> {
        // Index of the just-pushed prompt: the start of the unanswered user run
        // a cancellation before any provider answer truncates back to.
        let unanswered_start = self.messages.len();
        self.messages.push(Message::user(prompt));
        // The bare agent does no persistence: the harness diffs `messages()`
        // onto its session store after the turn returns (even on error).
        self.complete_turn(unanswered_start, obs, gate, env, token, steer)
            .await
    }

    async fn complete_turn(
        &mut self,
        unanswered_start: usize,
        obs: &dyn AgentObserver,
        gate: &dyn ApprovalGate,
        env: &ToolEnv<'_>,
        token: &CancellationToken,
        steer: Option<&dyn SteeringSource>,
    ) -> Result<()> {
        // Start of the current unanswered user-message run (the prompt, plus any
        // injected steering/follow-up not yet answered by the provider). Cleared
        // once a provider turn commits assistant content; a cancellation before
        // that truncates exactly this run so no dangling trailing user message is
        // persisted. Replaces the old `roundtrip == 0` heuristic, which could not
        // see injected messages.
        let mut unanswered_start: Option<usize> = Some(unanswered_start);
        // Unbounded by default: the loop ends when the model stops emitting
        // tool calls (or on cancellation). An optional configured soft cap
        // ends the turn gracefully after that many round-trips.
        let mut roundtrip = 0usize;
        loop {
            if let Some(cap) = self.max_tool_roundtrips
                && roundtrip >= cap
            {
                tracing::warn!(cap, "tool round-trip soft cap reached; ending turn");
                // Reached the configured soft cap while the model still wants
                // to call tools. End the turn gracefully so completed tool work
                // and conversation state are preserved and the REPL keeps
                // running; this is a soft limit, not a provider failure.
                obs.on_event(AgentEvent::Notice(format!(
                    "stopped after {cap} tool round-trips; send another message to continue."
                )))?;
                obs.on_event(AgentEvent::TurnComplete)?;
                return Ok(());
            }
            if token.is_cancelled() {
                tracing::info!(roundtrips = roundtrip, "turn interrupted by user");
                // Drop any unanswered user run (the prompt and/or injected
                // steering/follow-up not yet answered) so the next turn does not
                // push two consecutive user messages (rejected by some
                // providers) or persist a dangling trailing user message.
                if let Some(start) = unanswered_start {
                    self.messages.truncate(start);
                }
                self.emit_interrupted(obs)?;
                return Ok(());
            }

            // Inject any queued steering before this provider request. Covers the
            // initial poll (the user may have typed while the turn was starting)
            // and the post-tool poll (steering queued while the prior round's
            // tools ran). Mirrors pi polling `getSteeringMessages` before each
            // assistant response.
            if let Some(src) = steer {
                self.inject_user(src.take_steering(), obs, &mut unanswered_start)?;
            }

            let provider_turn_id = self.next_provider_turn_id();
            obs.on_event(AgentEvent::ProviderTurnStarted {
                turn_id: provider_turn_id.clone(),
            })?;

            let stream_result = match self.stream_turn(obs, token).await {
                Ok(result) => result,
                Err(error) => {
                    obs.on_event(AgentEvent::ProviderTurnError {
                        turn_id: provider_turn_id.clone(),
                        message: format!("{error:#}"),
                    })?;
                    return Err(error);
                }
            };

            match stream_result {
                StreamResult::Cancelled { partial, saw_delta } => {
                    // Commit any partial assistant text so the transcript stays
                    // valid (it answers the unanswered user run); otherwise drop
                    // that whole run (prompt and/or injected steering/follow-up).
                    if !partial.is_empty() {
                        if saw_delta {
                            obs.on_event(AgentEvent::AssistantTextEnd(partial.clone()))?;
                        } else {
                            obs.on_event(AgentEvent::AssistantText(partial.clone()))?;
                        }
                        self.messages.push(
                            Message::assistant(&partial).with_provider_turn_id(&provider_turn_id),
                        );
                    } else if let Some(start) = unanswered_start {
                        self.messages.truncate(start);
                    }
                    tracing::info!(
                        roundtrips = roundtrip,
                        "turn interrupted during model stream"
                    );
                    obs.on_event(AgentEvent::ProviderTurnCancelled {
                        turn_id: provider_turn_id.clone(),
                    })?;
                    self.emit_interrupted(obs)?;
                    return Ok(());
                }
                StreamResult::Completed { turn, saw_delta } => {
                    let AssistantTurn {
                        text,
                        reasoning,
                        tool_calls,
                        response_id,
                        usage,
                        completion_reason,
                    } = turn;
                    // Captured before `reasoning` is consumed below: drives
                    // whether a content-less completion (e.g. a bare refusal)
                    // needs an explanatory notice.
                    let had_visible_content = text.as_deref().is_some_and(|t| !t.is_empty())
                        || !tool_calls.is_empty()
                        || !reasoning.is_empty();
                    for block in reasoning {
                        // Surface reasoning for display WITHOUT changing storage:
                        // the row is still persisted below exactly as before
                        // (ADR-0016 continuity/redacted handling is untouched).
                        // Redacted blocks never carry their text downstream.
                        if block.redacted {
                            obs.on_event(AgentEvent::AssistantReasoning {
                                text: String::new(),
                                redacted: true,
                            })?;
                        } else if !block.text.is_empty() {
                            obs.on_event(AgentEvent::AssistantReasoning {
                                text: block.text.clone(),
                                redacted: false,
                            })?;
                        }
                        self.messages.push(
                            Message::assistant_reasoning_block(block)
                                .with_provider_turn_id(&provider_turn_id),
                        );
                    }
                    if let Some(text) = text.as_deref().filter(|text| !text.is_empty()) {
                        if saw_delta {
                            obs.on_event(AgentEvent::AssistantTextEnd(text.to_string()))?;
                        } else {
                            obs.on_event(AgentEvent::AssistantText(text.to_string()))?;
                        }
                        self.messages.push(
                            Message::assistant(text).with_provider_turn_id(&provider_turn_id),
                        );
                    } else if saw_delta {
                        obs.on_event(AgentEvent::AssistantTextEnd(String::new()))?;
                    }

                    // A completed provider turn answers the current unanswered
                    // user run: a later cancellation must not truncate it.
                    unanswered_start = None;

                    obs.on_event(AgentEvent::ProviderTurnCompleted {
                        turn_id: provider_turn_id.clone(),
                        response_id,
                        usage,
                        completion_reason,
                    })?;
                    // Surface notable completions (truncation, content-less
                    // refusal) to the user. Provider-neutral: driven by the
                    // typed completion metadata, not any provider-specific
                    // stop-reason string.
                    if let Some(notice) = completion_reason
                        .and_then(|reason| completion_reason_notice(reason, had_visible_content))
                    {
                        obs.on_event(AgentEvent::Notice(notice.to_string()))?;
                    }
                    if tool_calls.is_empty() {
                        // The agent would stop here. Steering queued during this
                        // (tool-less) response runs first, then follow-up. Either
                        // keeps the loop alive with another turn; with neither,
                        // the turn is complete. Mirrors pi polling steering after
                        // every turn and follow-up only at the stop point.
                        let injected = match steer {
                            Some(src) => {
                                let steering = src.take_steering();
                                if steering.is_empty() {
                                    src.take_follow_up()
                                } else {
                                    steering
                                }
                            }
                            None => Vec::new(),
                        };
                        if injected.is_empty() {
                            tracing::debug!(roundtrips = roundtrip + 1, "turn complete");
                            obs.on_event(AgentEvent::TurnComplete)?;
                            return Ok(());
                        }
                        self.inject_user(injected, obs, &mut unanswered_start)?;
                        // A tool-less steering/follow-up continuation is not a
                        // tool round-trip, so it must not advance the soft-cap
                        // counter: counting it could trip the cap check at the
                        // top of the next iteration and return before the
                        // provider ever answers the injected message, leaving a
                        // dangling unanswered user message. The injected turn
                        // still gets a provider response; only genuine tool
                        // rounds (below) advance the counter.
                        continue;
                    }
                    for call in &tool_calls {
                        self.messages.push(
                            Message::assistant_tool_call(call)
                                .with_provider_turn_id(&provider_turn_id),
                        );
                    }

                    match self
                        .run_tools(tool_calls, obs, gate, env, token, &provider_turn_id)
                        .await?
                    {
                        ToolsPhase::Ended => return Ok(()),
                        ToolsPhase::Continue => {}
                    }
                }
            }
            roundtrip += 1;
        }
    }

    /// Inject the host-queued user messages drained at one injection point
    /// (steering or follow-up) and announce them so the front-end renders the
    /// user row in transcript order. Enforces the transcript invariant "no two
    /// consecutive same-role user messages" (some providers reject them, others
    /// only coalesce on the wire): a batch drained together is merged with
    /// `\n\n`, and if the turn's trailing message is already a user message (the
    /// just-pushed prompt, or an earlier injection this turn) the merged text
    /// extends it in place rather than pushing a second user message. That
    /// trailing user is always from the current turn -- a completed turn ends on
    /// assistant content and a cancellation truncates its unanswered user run --
    /// so mutating it stays consistent with the harness's post-turn persistence
    /// diff. Sets `unanswered_start` to the start of the unanswered run so a
    /// cancellation before the provider answers truncates exactly these messages
    /// and never an answered one. The announced event carries only the newly
    /// injected text so it renders as its own row. A no-op for an empty batch,
    /// so it never spuriously starts an unanswered run.
    fn inject_user(
        &mut self,
        messages: Vec<String>,
        obs: &dyn AgentObserver,
        unanswered_start: &mut Option<usize>,
    ) -> Result<()> {
        if messages.is_empty() {
            return Ok(());
        }
        let text = messages.join("\n\n");
        if self
            .messages
            .last()
            .is_some_and(|last| last.role == Role::User)
        {
            let idx = self.messages.len() - 1;
            let last = &mut self.messages[idx];
            last.content.push_str("\n\n");
            last.content.push_str(&text);
            if unanswered_start.is_none() {
                *unanswered_start = Some(idx);
            }
        } else {
            if unanswered_start.is_none() {
                *unanswered_start = Some(self.messages.len());
            }
            self.messages.push(Message::user(&text));
        }
        obs.on_event(AgentEvent::UserMessage(text))?;
        Ok(())
    }

    /// Consume one provider stream to its terminal event, emitting text deltas
    /// and racing every read against cancellation. Borrows `&self` (messages +
    /// tools) only for the stream's lifetime; the owned [`StreamResult`] lets
    /// the caller mutate the transcript afterward.
    async fn stream_turn(
        &self,
        obs: &dyn AgentObserver,
        token: &CancellationToken,
    ) -> Result<StreamResult> {
        let mut stream = self
            .provider
            .respond_stream(&self.messages, &self.tools, token)?;
        let mut saw_delta = false;
        let mut partial = String::new();
        loop {
            tokio::select! {
                biased;
                _ = token.cancelled() => {
                    return Ok(StreamResult::Cancelled { partial, saw_delta });
                }
                item = stream.next() => match item {
                    Some(Ok(ProviderEvent::TextDelta(delta))) => {
                        saw_delta = true;
                        partial.push_str(&delta);
                        obs.on_event(AgentEvent::AssistantTextDelta(delta))?;
                    }
                    Some(Ok(ProviderEvent::Completed(turn))) => {
                        return Ok(StreamResult::Completed { turn, saw_delta });
                    }
                    Some(Err(error)) => return Err(error),
                    None => bail!("provider stream closed before completion"),
                },
            }
        }
    }

    /// Execute the model's tool calls: consecutive concurrency-safe calls run in
    /// parallel, every other call runs exclusively (one at a time). Transcript
    /// order is preserved regardless of completion order. On cancellation, every
    /// not-yet-executed call still gets a synthetic cancelled result so the next
    /// model request stays valid.
    async fn run_tools(
        &mut self,
        calls: Vec<ToolCall>,
        obs: &dyn AgentObserver,
        gate: &dyn ApprovalGate,
        env: &ToolEnv<'_>,
        token: &CancellationToken,
        provider_turn_id: &str,
    ) -> Result<ToolsPhase> {
        let store = env.output_store;
        let mut idx = 0;
        while idx < calls.len() {
            if token.is_cancelled() {
                tracing::info!(
                    pending = calls.len() - idx,
                    "turn interrupted during tools; remaining calls cancelled"
                );
                for call in &calls[idx..] {
                    emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Proposed)?;
                    record_call(
                        &mut self.messages,
                        obs,
                        store,
                        call,
                        ToolOutcome::Cancelled,
                        provider_turn_id,
                    )?;
                }
                self.emit_interrupted(obs)?;
                return Ok(ToolsPhase::Ended);
            }

            if self.is_parallelizable(&calls[idx]) {
                let mut end = idx;
                while end < calls.len() && self.is_parallelizable(&calls[end]) {
                    end += 1;
                }
                for call in &calls[idx..end] {
                    obs.on_event(AgentEvent::ToolProposed(call.clone()))?;
                    emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Proposed)?;
                    obs.on_event(AgentEvent::ToolStarted(call.clone()))?;
                    emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Started)?;
                }
                // Scope the borrow of `self.tools` so it drops before the
                // transcript pushes below.
                let outcomes = run_parallel(&self.tools, &calls[idx..end], env, token).await;
                for (call, outcome) in calls[idx..end].iter().zip(outcomes) {
                    record_call(
                        &mut self.messages,
                        obs,
                        store,
                        call,
                        outcome,
                        provider_turn_id,
                    )?;
                }
                idx = end;
            } else {
                let outcome = self
                    .run_gated_single(&calls[idx], obs, gate, env, token, provider_turn_id)
                    .await?;
                record_call(
                    &mut self.messages,
                    obs,
                    store,
                    &calls[idx],
                    outcome,
                    provider_turn_id,
                )?;
                idx += 1;
            }
        }

        // The model gets another round-trip to react to the tool results; the
        // turn is not complete here (only an empty tool-call response, the
        // round-trip cap, or a cancellation ends it).
        Ok(ToolsPhase::Continue)
    }

    /// Whether a call may join a parallel batch: it resolves to a known tool
    /// that is concurrency-safe and ungated. Gated tools always take the
    /// exclusive path so their approval prompt runs alone.
    fn is_parallelizable(&self, call: &ToolCall) -> bool {
        self.tools
            .by_name(&call.name)
            .is_some_and(|tool| tool.is_concurrency_safe() && !tool.requires_approval())
    }

    /// The exclusive (default) path for one call: approval policy, then a single
    /// cancellation-raced execution. Returns the outcome; the caller records it.
    async fn run_gated_single(
        &mut self,
        call: &ToolCall,
        obs: &dyn AgentObserver,
        gate: &dyn ApprovalGate,
        env: &ToolEnv<'_>,
        token: &CancellationToken,
        provider_turn_id: &str,
    ) -> Result<ToolOutcome> {
        emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Proposed)?;
        if let Some(tool) = self.tools.by_name(&call.name) {
            if let Some(diff) = tool.diff_preview(env.workspace, &call.arguments) {
                obs.on_event(AgentEvent::DiffPreview {
                    call: call.clone(),
                    diff,
                })?;
            }
            if !tool.requires_approval() {
                obs.on_event(AgentEvent::ToolProposed(call.clone()))?;
            } else {
                // A destructive call (e.g. `rm`) always re-prompts, even when its
                // tool was "always allowed" this session: a blanket bash allow must
                // not silently auto-run data-losing commands.
                let destructive = tool.is_destructive(&call.arguments);
                let session_allowed = self.session_allowed.contains(&call.name);
                let auto_approved = session_allowed && !destructive && tool.supports_allow_always();
                if auto_approved {
                    obs.on_event(AgentEvent::ToolAutoApproved(call.clone()))?;
                    emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Approved)?;
                }
                if !auto_approved {
                    if destructive && session_allowed {
                        let message = "destructive command: approval required even though this tool is allow-always";
                        obs.on_event(AgentEvent::Notice(message.to_string()))?;
                    }
                    // Race the approval against cancellation so a pending prompt
                    // does not pin the turn open after a Ctrl-C. Cancellation is
                    // recorded as a cancelled call (not a denial) so the transcript
                    // reflects user intent rather than a refusal.
                    emit_tool_lifecycle(
                        obs,
                        provider_turn_id,
                        call,
                        ToolEventState::ApprovalRequested,
                    )?;
                    let decision = tokio::select! {
                        biased;
                        _ = token.cancelled() => return Ok(ToolOutcome::Cancelled),
                        decision = gate.review(call, tool.supports_allow_always()) => decision?,
                    };
                    // A blocking front-end prompt (real terminal) cannot observe
                    // the token mid-read, so it may still return a decision after a
                    // Ctrl-C landed. Treat the turn cancellation as authoritative so
                    // a late Allow/Deny neither runs the tool nor mutates the
                    // session allow-policy.
                    if token.is_cancelled() {
                        return Ok(ToolOutcome::Cancelled);
                    }
                    match decision {
                        ApprovalDecision::Deny => {
                            tracing::warn!(tool = %call.name, "tool call denied by user");
                            return Ok(ToolOutcome::Denied);
                        }
                        ApprovalDecision::AllowAlways => {
                            if tool.supports_allow_always() {
                                tracing::info!(tool = %call.name, "tool always-allowed this session");
                                self.session_allowed.insert(call.name.clone());
                            } else {
                                let message = format!(
                                    "always-allow is disabled for `{}`; it requires approval each time.",
                                    call.name
                                );
                                obs.on_event(AgentEvent::Notice(message))?;
                            }
                        }
                        ApprovalDecision::Allow => {}
                    }
                    emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Approved)?;
                }
            }
        } else {
            obs.on_event(AgentEvent::ToolProposed(call.clone()))?;
        }

        // Resolve again for execution (the approval borrow above has ended); an
        // unknown tool yields the same `unknown tool: <name>` result as before.
        let outcome = match self.tools.by_name(&call.name) {
            Some(tool) => {
                // Announce execution start (so a front-end opens a live cell)
                // only for a real tool, then inject a per-call streaming emitter
                // for the run. An unknown tool never opens a phantom cell and
                // keeps an exact ToolStarted/ToolResult pairing. Only this
                // exclusive path streams (the parallel/exploration path stays
                // sink-less), so a single live exec cell is always enough.
                obs.on_event(AgentEvent::ToolStarted(call.clone()))?;
                emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Started)?;
                let emitter = ToolDeltaEmitter {
                    obs,
                    call_id: call.id.clone(),
                };
                let call_env = ToolEnv {
                    workspace: env.workspace,
                    state: env.state,
                    output_store: env.output_store,
                    output_sink: Some(&emitter),
                };
                run_tool(tool, &call.arguments, &call_env, token.child_token()).await
            }
            None => ToolOutcome::Err(anyhow::anyhow!("unknown tool: {}", call.name)),
        };
        Ok(outcome)
    }

    fn emit_interrupted(&self, obs: &dyn AgentObserver) -> Result<()> {
        obs.on_event(AgentEvent::Notice(INTERRUPT_NOTICE.to_string()))?;
        obs.on_event(AgentEvent::TurnComplete)
    }

    fn next_provider_turn_id(&mut self) -> String {
        let id = format!("turn_{:08x}", self.next_provider_turn_seq);
        self.next_provider_turn_seq += 1;
        id
    }
}

/// Per-call streaming emitter injected into a tool's [`ToolEnv`] on the
/// exclusive execution path. Forwards each chunk the tool produces to the
/// observer as a display-only [`AgentEvent::ToolOutputDelta`] tagged with the
/// call id, so the front-end attaches the live output to the right cell. The
/// observer error is intentionally swallowed: a streamed-progress delivery
/// failure must not abort the tool, whose final result still flows through
/// [`record_call`].
struct ToolDeltaEmitter<'a> {
    obs: &'a dyn AgentObserver,
    call_id: String,
}

impl ToolOutputSink for ToolDeltaEmitter<'_> {
    fn emit_chunk(&self, chunk: &str) {
        let _ = self.obs.on_event(AgentEvent::ToolOutputDelta {
            call_id: self.call_id.clone(),
            chunk: chunk.to_string(),
        });
    }
}

/// Run a bounded batch of concurrency-safe calls concurrently, returning outcomes
/// in the same order as `calls`. Each call gets its own child cancellation token.
/// Uses ordered buffering (not `tokio::spawn`) so the `!Send` borrowed futures run
/// on the loop's executor without queuing unbounded blocking work.
async fn run_parallel(
    tools: &Tools,
    calls: &[ToolCall],
    env: &ToolEnv<'_>,
    token: &CancellationToken,
) -> Vec<ToolOutcome> {
    futures::stream::iter(calls.iter())
        .map(|call| {
            let cancel = token.child_token();
            async move {
                match tools.by_name(&call.name) {
                    Some(tool) => run_tool(tool, &call.arguments, env, cancel).await,
                    None => ToolOutcome::Err(anyhow::anyhow!("unknown tool: {}", call.name)),
                }
            }
        })
        // No fixed parallelism cap: every parallelizable call in the batch runs
        // concurrently (matching pi-mono's `Promise.all` over the batch).
        // `buffered` (not `buffer_unordered`) preserves result order, which the
        // caller zips back onto the calls. `max(1)` guards the empty-batch case
        // (`buffered(0)` would stall); run_tools only calls this with a
        // non-empty parallelizable run.
        .buffered(calls.len().max(1))
        .collect()
        .await
}

/// Run one tool, racing its future against the (child) cancellation token. The
/// pre-check matters: a synchronous tool body would otherwise run to completion
/// on the first poll even when already cancelled (the select is `biased` toward
/// the tool so a cooperative tool's own result wins over the synthetic one). The
/// post-check maps sync tools that observe cancellation internally to the same
/// transcript-valid cancelled outcome.
async fn run_tool<'a>(
    tool: &'a dyn Tool,
    args: &'a Value,
    env: &'a ToolEnv<'_>,
    cancel: CancellationToken,
) -> ToolOutcome {
    if cancel.is_cancelled() {
        return ToolOutcome::Cancelled;
    }
    tokio::select! {
        biased;
        result = tool.execute(args, env, cancel.clone()) => match result {
            _ if cancel.is_cancelled() => ToolOutcome::Cancelled,
            Ok(output) => ToolOutcome::Ok(output),
            Err(error) => ToolOutcome::Err(error),
        },
        _ = cancel.cancelled() => ToolOutcome::Cancelled,
    }
}

fn emit_tool_lifecycle(
    obs: &dyn AgentObserver,
    provider_turn_id: &str,
    call: &ToolCall,
    state: ToolEventState,
) -> Result<()> {
    obs.on_event(AgentEvent::ToolLifecycle {
        provider_turn_id: provider_turn_id.to_string(),
        call_id: call.id.clone(),
        name: call.name.clone(),
        state,
    })
}

/// Stable host metadata for an oversized tool output stored out of provider
/// context. This is safe to persist and emit because it carries only the handle
/// id and already-computed size/count data, never the full body or preview.
#[derive(Debug, Clone, PartialEq, Eq)]
struct OutputHandleMetadata {
    id: String,
    bytes: usize,
    lines: usize,
}

impl OutputHandleMetadata {
    fn to_value(&self) -> Value {
        json!({ "id": self.id, "bytes": self.bytes, "lines": self.lines })
    }
}

/// Provider-neutral model-facing tool-result envelope. Concrete tools own the
/// `content` text and optional metadata fields; Nexus owns how those values are
/// serialized into provider-visible success/error/denied/cancelled results.
///
/// Keep this narrow and Rust-native: it documents and enforces today's wire
/// shape without adding Flue-style schema generation or a public plugin API.
#[derive(Debug)]
enum ToolResultContract {
    Success(ToolOutput),
    ToolError(Error),
    Denied,
    Cancelled,
}

impl ToolResultContract {
    fn success(output: ToolOutput) -> Self {
        Self::Success(output)
    }

    fn tool_error(error: Error) -> Self {
        Self::ToolError(error)
    }

    fn denied() -> Self {
        Self::Denied
    }

    fn cancelled() -> Self {
        Self::Cancelled
    }

    fn into_wire_json(self) -> String {
        self.into_wire_value().to_string()
    }

    fn into_wire_value(self) -> Value {
        match self {
            Self::Success(output) => {
                let mut obj = serde_json::Map::new();
                obj.insert("ok".to_string(), Value::Bool(true));
                obj.insert("content".to_string(), Value::String(output.content));
                if !output.metadata.is_empty() {
                    obj.insert("metadata".to_string(), Value::Object(output.metadata));
                }
                Value::Object(obj)
            }
            Self::ToolError(error) => json!({ "ok": false, "error": error.to_string() }),
            Self::Denied => json!({
                "ok": false,
                "error": "tool call denied by user",
                "denied": true
            }),
            Self::Cancelled => json!({
                "ok": false,
                "error": "tool call cancelled by user",
                "cancelled": true
            }),
        }
    }
}

/// Append one tool call and its result to the transcript and emit the matching
/// event. Every model-emitted call goes through here exactly once, so the
/// assistant-tool-call / tool-result pairing is always complete.
fn record_call(
    messages: &mut Vec<Message>,
    obs: &dyn AgentObserver,
    store: Option<&dyn ToolOutputStore>,
    call: &ToolCall,
    outcome: ToolOutcome,
    provider_turn_id: &str,
) -> Result<()> {
    // Append the tool result BEFORE emitting the observer event. An observer
    // error must not skip the provider-visible result for a call that already
    // ran; Wayland persists the transcript even on a turn error.
    let event = match outcome {
        ToolOutcome::Ok(mut output) => {
            tracing::info!(tool = %call.name, ok = true, "tool executed");
            // The observer still receives the full output: offloading only keeps
            // the oversized payload out of provider context, never out of the
            // user-facing display (which folds it to a preview itself).
            let content = output.content.clone();
            // Lift the display-only exec metadata out of the output BEFORE
            // serialization so the non-deterministic duration and the exit code
            // ride the event, never entering provider context (and the wire
            // shape stays byte-identical to a plain text-only result).
            let exit_code = output
                .metadata
                .remove("exitCode")
                .and_then(|value| value.as_i64())
                .map(|code| code as i32);
            let duration = output
                .metadata
                .remove("durationMs")
                .and_then(|value| value.as_u64())
                .map(Duration::from_millis);
            let (result_json, handle) = success_tool_result_json(store, output);
            messages.push(
                Message::tool_result(&call.id, &call.name, &result_json)
                    .with_provider_turn_id(provider_turn_id),
            );
            if let Some(handle) = handle {
                obs.on_event(AgentEvent::OutputHandleStored {
                    provider_turn_id: provider_turn_id.to_string(),
                    call_id: call.id.clone(),
                    handle_id: handle.id,
                    bytes: handle.bytes,
                    lines: handle.lines,
                })?;
            }
            emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Succeeded)?;
            AgentEvent::ToolResult {
                call: call.clone(),
                content,
                exit_code,
                duration,
            }
        }
        ToolOutcome::Err(error) => {
            tracing::info!(tool = %call.name, ok = false, "tool executed");
            let message = format!("{error:#}");
            messages.push(
                Message::tool_result(
                    &call.id,
                    &call.name,
                    &ToolResultContract::tool_error(error).into_wire_json(),
                )
                .with_provider_turn_id(provider_turn_id),
            );
            emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Errored)?;
            AgentEvent::ToolError {
                call: call.clone(),
                message,
            }
        }
        ToolOutcome::Cancelled => {
            tracing::info!(tool = %call.name, "tool cancelled");
            messages.push(
                Message::tool_result(
                    &call.id,
                    &call.name,
                    &ToolResultContract::cancelled().into_wire_json(),
                )
                .with_provider_turn_id(provider_turn_id),
            );
            emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Cancelled)?;
            AgentEvent::ToolCancelled(call.clone())
        }
        ToolOutcome::Denied => {
            tracing::warn!(tool = %call.name, "tool call denied");
            messages.push(
                Message::tool_result(
                    &call.id,
                    &call.name,
                    &ToolResultContract::denied().into_wire_json(),
                )
                .with_provider_turn_id(provider_turn_id),
            );
            emit_tool_lifecycle(obs, provider_turn_id, call, ToolEventState::Denied)?;
            AgentEvent::ToolDenied(call.clone())
        }
    };
    obs.on_event(event)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ProviderUsage {
    pub(crate) provider: String,
    pub(crate) model: String,
    /// Total provider-visible input tokens, including cache reads/writes when
    /// the provider reports them separately.
    pub(crate) input_tokens: u64,
    pub(crate) output_tokens: u64,
    /// Input tokens served from prompt cache. Already included in
    /// `input_tokens`; callers must not add them again when computing total
    /// input.
    pub(crate) cache_read_input_tokens: u64,
    pub(crate) cache_write_input_tokens: u64,
    pub(crate) reasoning_output_tokens: u64,
    pub(crate) total_tokens: u64,
    /// Provider breakdown of cache-creation (write) tokens by retention class,
    /// when reported. Anthropic surfaces this as `usage.cache_creation`
    /// (`ephemeral_5m_input_tokens` / `ephemeral_1h_input_tokens`); providers
    /// that do not report a breakdown leave this `None`. The component totals
    /// are already summed into `cache_write_input_tokens`.
    pub(crate) cache_creation: Option<CacheCreation>,
}

/// Per-retention breakdown of prompt-cache-creation (write) input tokens, as
/// reported by Anthropic's `usage.cache_creation` detail. Surfaced alongside
/// the `cache_write_input_tokens` total so diagnostics can attribute writes to
/// the 5-minute vs 1-hour cache tier.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct CacheCreation {
    pub(crate) ephemeral_5m_input_tokens: u64,
    pub(crate) ephemeral_1h_input_tokens: u64,
}

/// Provider-neutral reason a model turn completed, mapped from the provider's
/// terminal stop signal (e.g. Anthropic `message_delta.delta.stop_reason`).
/// Carried as safe completion metadata on [`AssistantTurn`] and
/// [`AgentEvent::ProviderTurnCompleted`]; every variant is an enumerated
/// classification and never carries response text. Stop reasons Iris does not
/// model yet map to `Other` (the raw wire token is logged at parse time rather
/// than stored, keeping this a small `Copy` enum).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CompletionReason {
    /// Natural end of the assistant turn.
    EndTurn,
    /// The model stopped to call one or more tools.
    ToolUse,
    /// Output was truncated at the requested max output-token ceiling.
    MaxOutputTokens,
    /// The model's input context window was exceeded.
    ContextWindowExceeded,
    /// A configured stop sequence was emitted.
    StopSequence,
    /// The provider paused a long-running turn and expects continuation.
    Paused,
    /// The model declined to continue (safety refusal).
    Refusal,
    /// A stop reason Iris does not model yet. The raw enumerated wire token is
    /// logged at parse time rather than stored.
    Other,
}

/// Provider-neutral, user-facing notice for a completion reason the user should
/// know about. Returns `None` for routine reasons that need no notice. Wording
/// stays model-agnostic so it is correct for any provider; the runtime never
/// hard-codes a provider/model name here.
///
/// `had_visible_content` is whether the turn produced any text, reasoning, or
/// tool calls: a refusal that carried an explanation needs no extra notice (the
/// user already sees why), but a content-less refusal would otherwise be silent.
pub(crate) fn completion_reason_notice(
    reason: CompletionReason,
    had_visible_content: bool,
) -> Option<&'static str> {
    match reason {
        CompletionReason::MaxOutputTokens => {
            Some("The model hit its maximum output-token limit; this response may be truncated.")
        }
        CompletionReason::ContextWindowExceeded => {
            Some("The model reached its context-window limit; this response may be truncated.")
        }
        CompletionReason::Refusal if !had_visible_content => Some("The model declined to respond."),
        _ => None,
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct AssistantTurn {
    pub(crate) text: Option<String>,
    pub(crate) reasoning: Vec<ReasoningBlock>,
    pub(crate) tool_calls: Vec<ToolCall>,
    pub(crate) response_id: Option<String>,
    pub(crate) usage: Option<ProviderUsage>,
    /// Provider-neutral completion reason, when the provider reports one.
    pub(crate) completion_reason: Option<CompletionReason>,
}

impl AssistantTurn {
    #[cfg(test)]
    pub(crate) fn text(text: &str) -> Self {
        Self {
            text: Some(text.to_string()),
            ..Self::default()
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ModelOrigin {
    pub(crate) provider: String,
    pub(crate) api: String,
    pub(crate) model: String,
}

impl ModelOrigin {
    pub(crate) fn new(provider: &str, api: &str, model: &str) -> Self {
        Self {
            provider: provider.to_string(),
            api: api.to_string(),
            model: model.to_string(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ReasoningBlock {
    pub(crate) text: String,
    pub(crate) continuity: Option<String>,
    pub(crate) redacted: bool,
    pub(crate) origin: ModelOrigin,
}

impl ReasoningBlock {
    pub(crate) fn new(
        text: &str,
        continuity: Option<&str>,
        redacted: bool,
        origin: ModelOrigin,
    ) -> Self {
        Self {
            text: text.to_string(),
            continuity: continuity.map(str::to_string),
            redacted,
            origin,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ToolCall {
    pub(crate) id: String,
    pub(crate) name: String,
    pub(crate) arguments: Value,
    // Opaque provider continuity token for this call (e.g. Gemini's
    // `thoughtSignature`). Echoed back verbatim in the next request's history so
    // thinking models accept the tool round-trip; `None` for providers that do
    // not emit one. Nexus never interprets it.
    pub(crate) thought_signature: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Message {
    pub(crate) role: Role,
    pub(crate) content: String,
    // Tool-call and tool-result messages must carry both fields; text messages leave them empty.
    pub(crate) tool_call_id: Option<String>,
    pub(crate) tool_name: Option<String>,
    // Provider-neutral reasoning continuity. Only AssistantReasoning rows use
    // these; Nexus stores them opaquely and never interprets signatures/data.
    pub(crate) continuity: Option<String>,
    // Nexus-owned provider/model round-trip id. Present on assistant/reasoning/
    // tool-call/tool-result messages produced by a provider turn; absent on
    // user messages and legacy resumed entries.
    pub(crate) provider_turn_id: Option<String>,
    pub(crate) redacted: bool,
    pub(crate) origin: Option<ModelOrigin>,
}

impl Message {
    pub(crate) fn user(content: &str) -> Self {
        Self::new(Role::User, content)
    }

    pub(crate) fn assistant(content: &str) -> Self {
        Self::new(Role::Assistant, content)
    }

    #[cfg(test)]
    pub(crate) fn assistant_reasoning(
        content: &str,
        continuity: &str,
        redacted: bool,
        origin: ModelOrigin,
    ) -> Self {
        Self::assistant_reasoning_block(ReasoningBlock::new(
            content,
            Some(continuity),
            redacted,
            origin,
        ))
    }

    pub(crate) fn assistant_reasoning_block(block: ReasoningBlock) -> Self {
        Self {
            role: Role::AssistantReasoning,
            content: block.text,
            tool_call_id: None,
            tool_name: None,
            continuity: block.continuity,
            provider_turn_id: None,
            redacted: block.redacted,
            origin: Some(block.origin),
        }
    }

    pub(crate) fn assistant_tool_call(call: &ToolCall) -> Self {
        Self {
            role: Role::AssistantToolCall,
            content: call.arguments.to_string(),
            tool_call_id: Some(call.id.clone()),
            tool_name: Some(call.name.clone()),
            // Carry the provider's opaque per-call continuity (e.g. Gemini
            // `thoughtSignature`) so it survives persistence and is echoed back.
            continuity: call.thought_signature.clone(),
            provider_turn_id: None,
            redacted: false,
            origin: None,
        }
    }

    fn tool_result(call_id: &str, name: &str, content: &str) -> Self {
        Self {
            role: Role::Tool,
            content: content.to_string(),
            tool_call_id: Some(call_id.to_string()),
            tool_name: Some(name.to_string()),
            continuity: None,
            provider_turn_id: None,
            redacted: false,
            origin: None,
        }
    }

    fn new(role: Role, content: &str) -> Self {
        Self {
            role,
            content: content.to_string(),
            tool_call_id: None,
            tool_name: None,
            continuity: None,
            provider_turn_id: None,
            redacted: false,
            origin: None,
        }
    }

    pub(crate) fn with_provider_turn_id(mut self, provider_turn_id: &str) -> Self {
        self.provider_turn_id = Some(provider_turn_id.to_string());
        self
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Role {
    User,
    Assistant,
    AssistantReasoning,
    AssistantToolCall,
    Tool,
}

impl Role {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Assistant => "assistant",
            Self::AssistantReasoning => "assistant_reasoning",
            Self::AssistantToolCall => "assistant_tool_call",
            Self::Tool => "tool",
        }
    }

    /// Inverse of [`as_str`](Self::as_str): parse a persisted role string back
    /// into a `Role`. Used by the session store to reconstruct messages when
    /// reading a transcript. `None` for an unknown role.
    pub(crate) fn from_wire(role: &str) -> Option<Self> {
        match role {
            "user" => Some(Self::User),
            "assistant" => Some(Self::Assistant),
            "assistant_reasoning" => Some(Self::AssistantReasoning),
            "assistant_tool_call" => Some(Self::AssistantToolCall),
            "tool" => Some(Self::Tool),
            _ => None,
        }
    }
}

/// Pair a trailing tool call that has no recorded result. A prior session that
/// crashed between persisting an `AssistantToolCall` and its `Tool` result
/// leaves the call unanswered as the last entry; appending a new user prompt
/// then yields a sequence providers reject (every tool call must be answered).
/// At most one such call can dangle (the loop records each call's result
/// adjacently), so one synthetic result restores validity. The appended message
/// is new (beyond the persisted cursor), so the harness writes it to the same
/// log, keeping disk and memory consistent.
fn next_provider_turn_seq(messages: &[Message]) -> u32 {
    messages
        .iter()
        .filter_map(|message| message.provider_turn_id.as_deref())
        .filter_map(|id| id.strip_prefix("turn_"))
        .filter_map(|seq| u32::from_str_radix(seq, 16).ok())
        .max()
        .map_or(0, |seq| seq.saturating_add(1))
}

fn repair_dangling_tool_call(messages: &mut Vec<Message>) {
    let mut pending: Vec<(String, String, Option<String>)> = Vec::new();
    for message in messages.iter() {
        match message.role {
            Role::AssistantToolCall => {
                if let (Some(call_id), Some(name)) = (&message.tool_call_id, &message.tool_name) {
                    pending.push((
                        call_id.clone(),
                        name.clone(),
                        message.provider_turn_id.clone(),
                    ));
                }
            }
            Role::Tool => {
                if let Some(call_id) = &message.tool_call_id
                    && let Some(pos) = pending.iter().position(|(id, _, _)| id == call_id)
                {
                    pending.remove(pos);
                }
            }
            Role::User | Role::Assistant | Role::AssistantReasoning => {}
        }
    }
    for (call_id, name, provider_turn_id) in pending {
        let mut result = Message::tool_result(
            &call_id,
            &name,
            &ToolResultContract::cancelled().into_wire_json(),
        );
        result.provider_turn_id = provider_turn_id;
        messages.push(result);
    }
}

/// Build the model-facing JSON for a successful tool result, offloading the
/// content behind a handle when it is oversized and a store is available
/// (issue #61). Small outputs, and the fallback when no store exists or the
/// store write fails, are byte-identical to the original inline encoding -- the
/// full output is never truncated and discarded.
fn success_tool_result_json(
    store: Option<&dyn ToolOutputStore>,
    mut output: ToolOutput,
) -> (String, Option<OutputHandleMetadata>) {
    if output.content.len() <= MAX_INLINE_TOOL_OUTPUT_BYTES {
        return (ToolResultContract::success(output).into_wire_json(), None);
    }
    let Some(store) = store else {
        // No durable store (e.g. in-memory session): keep the full output inline
        // rather than lose it. Larger context, but never data loss.
        return (ToolResultContract::success(output).into_wire_json(), None);
    };
    match store.put(&output.content) {
        Ok(handle_id) => {
            // Swap the oversized content for a compact preview and record the
            // typed handle pointer in metadata, then serialize through the same
            // contract as an inline result -- one serialization path, so the
            // offloaded and inline shapes cannot drift apart.
            let total_bytes = output.content.len();
            let total_lines = output.content.lines().count();
            output.content = compact_preview(&output.content, &handle_id, total_bytes, total_lines);
            let info = OutputHandleMetadata {
                id: handle_id,
                bytes: total_bytes,
                lines: total_lines,
            };
            output
                .metadata
                .insert("outputHandle".to_string(), info.to_value());
            (
                ToolResultContract::success(output).into_wire_json(),
                Some(info),
            )
        }
        Err(error) => {
            tracing::warn!(
                error = %format!("{error:#}"),
                "tool output handle store failed; inlining full output"
            );
            (ToolResultContract::success(output).into_wire_json(), None)
        }
    }
}

// `compact_preview` is only reached for offloaded outputs, which by construction
// exceed MAX_INLINE_TOOL_OUTPUT_BYTES. This compile-time assert ties that to the
// preview sizing, so head and tail never overlap and `len - PREVIEW_TAIL_BYTES`
// never underflows -- tuning a constant that breaks the invariant fails the
// build instead of producing a malformed preview at runtime.
const _: () = assert!(MAX_INLINE_TOOL_OUTPUT_BYTES > PREVIEW_HEAD_BYTES + PREVIEW_TAIL_BYTES);

/// Head + tail of an oversized output with a middle-elision notice naming the
/// handle. Slices land on UTF-8 char boundaries via the stdlib boundary helpers;
/// head and tail are disjoint and the tail offset cannot underflow because an
/// offloaded output is strictly larger than `PREVIEW_HEAD_BYTES +
/// PREVIEW_TAIL_BYTES` (the const assert above).
fn compact_preview(
    content: &str,
    handle_id: &str,
    total_bytes: usize,
    total_lines: usize,
) -> String {
    let head = &content[..content.floor_char_boundary(PREVIEW_HEAD_BYTES)];
    let tail = &content[content.ceil_char_boundary(content.len() - PREVIEW_TAIL_BYTES)..];
    let omitted = total_bytes.saturating_sub(head.len() + tail.len());
    let notice = format!(
        "\n... [iris stored the full {total_bytes}-byte ({total_lines}-line) tool output out of \
         context; {omitted} bytes omitted here. retrieve via output handle {handle_id}] ...\n"
    );
    format!("{head}{notice}{tail}")
}

#[cfg(test)]
#[path = "nexus_tests.rs"]
mod tests;
